### ISSUE TITLE
构建项目出错

### ISSUE THREAD

**Issue by ZhengQuancheng** [WadeGao/rv64_emulator#60]
您好，执行 `xmake` 会出错，报错信息如下所示（与 `asmjit` 有关）：
![PixPin_2024-07-13_09-43-57](https://github.com/user-attachments/assets/c33088ee-f781-4cb6-b775-dea034a687f3)

**Comment by WadeGao** [comment]
我很久没有维护这个仓库了
1. 或许是克隆仓库时拉取了最新的子模块，asmjit库应该是在将命名空间换成了`asmjit::a64::GpX`，或许可以改一下试试。参见https://asmjit.com/doc/group__asmjit__a64.html
2. rv64_emulator项目的JIT功能属于半成品状态，只用在了单元测试中，在模拟器本体中并未启用。你可以删除与JIT相关的单元测试。

**Comment by ZhengQuancheng** [comment]
好嘞，谢谢您
